version: "2.1"
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        server_port: ${SERVER_PORT}
    depends_on:
    - mongo
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE: ${DATABASE}
      DB_HOST: ${DB_HOST}:${DB_PORT}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PATH: ${SERVER_PATH}
      SERVER_PORT: ${SERVER_PORT}
    links:
    - mongo
    networks:
    - backend
    ports:
    - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    volumes:
    - ./server:/app/server                   #for details check the link below
    - node_modules:/app/server/node_modules/ #https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder#answer-37898591
  mongo:
    command: mongod
    environment:
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
      AUTH_MECHANISM: ${AUTH_MECHANISM}
      DATABASE: ${DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: admin
    image: mongo
    networks:
    - backend
    ports:
    - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
    - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
networks:
  backend:
    driver: bridge
volumes:
  node_modules:   # refers to the node_modules folder inside ./server/