version: "2.1"
services:
  app:
    container_name: app
    restart: always
    build: ..
    ports:
    - "4000:4000"
    links:
    - mongo
    depends_on:
    - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
    - "27017:27017"