version: "2.1"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "4005:4005"
    links:
    - mongodb
    depends_on:
    - mongodb
    environment:
      WAIT_HOSTS: mongodb//:192.168.99.100:27017
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
    - "27017:27017"